use_frameworks!

target 'SDNetworking_Example' do
  pod 'SDNetworking', :path => '../'

  target 'SDNetworking_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
